[package]
authors = ["Ceri Storey <cez@necrofish.org.uk>"]
name = "sulfur"
version = "0.1.0"

[dependencies]
failure = "0.1.3"
reqwest = "0.9.4"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.32"
webdriver = "0.38.0"