[package]
authors = ["Ceri Storey <cez@necrofish.org.uk>"]
name = "sulfur"
version = "0.1.0"

[dependencies]
env_logger = "0.5.13"
failure = "0.1.3"
lazy_static = "1.2.0"
log = "0.4.6"
reqwest = "0.9.4"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.32"
url = "1.7.1"
